"""
Pydantic schemas for the Forge resource.

These schemas define the data validation and serialization for Forge-related API endpoints.
- ForgeBase: Shared fields for Forge creation and update.
- ForgeCreate: Fields required to create a new Forge (input validation).
- ForgeUpdate: Fields that can be updated for an existing Forge (partial update input).
- ForgeOut: Fields returned in API responses for a Forge (output serialization).
"""

from pydantic import BaseModel
from typing import Optional, Any
from datetime import datetime, date

class ForgeBase(BaseModel):
    """
    Base schema for Forge, containing common fields used in creation and update.
    Purpose: Provides a foundation for input validation and shared attributes between create and update operations.
    """
    name: str
    description: Optional[str] = None
    owner_id: str
    status: Optional[str] = "active"
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    members: Optional[Any] = None  # Can be List[Any], Dict[str, Any], etc.
    tags: Optional[Any] = None

class ForgeCreate(ForgeBase):
    """
    Schema for creating a new Forge.
    Purpose: Used for input validation when a client submits data to create a new Forge resource.
    Inherits all fields from ForgeBase.
    """
    pass

class ForgeUpdate(BaseModel):
    """
    Schema for updating an existing Forge.
    Purpose: Used for input validation when a client submits data to partially update an existing Forge resource. All fields are optional to allow partial updates.
    """
    name: Optional[str] = None
    description: Optional[str] = None
    owner_id: Optional[str] = None
    status: Optional[str] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    members: Optional[Any] = None
    tags: Optional[Any] = None

class ForgeOut(ForgeBase):
    """
    Schema for API responses representing a Forge, including database-generated fields.
    Purpose: Used for serializing and returning Forge data in API responses, including fields generated by the database (id, created_at, updated_at).
    Inherits all fields from ForgeBase and adds id, created_at, and updated_at.
    """
    id: str
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True
